### ISSUE TITLE
BFGMiner doesn't save clock speeds

### ISSUE THREAD

**Issue by tortib** [luke-jr/bfgminer#147]
I recently set my memory clock speeds to 800MHz on all 3 of my video cards when BFGMiner was running, saved my settings.  Then went into the config to look at the gpu-memclock settings and it showed them all as "gpu-memclock" : "0,0,0"

Once I hard coded the "gpu-memclock": "800,800,800" and restarted BFGMiner the settings took.  It looks like the settings are not being saved properly when setting the clock speeds and then saving the settings to a configuration file.

**Comment by luke-jr** [comment]
Should be fixed in 3bb3fda. Please confirm.

**Comment by subSTRATA** [comment]
2.9.3 still having the issue. Setting GPU engine in miner and saving changes does not overwrite values at .conf file.

**Comment by evanrich** [comment]
This is still an issue a year later with 3.8.0
